//
//  HomeModels.swift
//  VuduTV
//
//  Created by Mcbook Pro on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
  // MARK: Use cases
  
  enum Movies
  {
      
    struct Request
    {
    }
    struct Response
    {
        var movies: [Title ]
    }
    struct ViewModel
    {
        var movies: [Title ]
    }
      
  }
    
    enum MoviePreview {
        
        struct Request
        {
            var moviePreviewModel: TitlePreviewViewModel
        }
        struct Response
        {
           
        }
        struct ViewModel
        {
          
        }
    }
}

