//
//  HomePresenter.swift
//  VuduTV
//
//  Created by Mcbook Pro on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentMovies(response: Home.Movies.Response)
    func presentTrendingTv(response: Home.Movies.Response)
    func presentPopular(response: Home.Movies.Response)
    func presentUpcomingMovies(response: Home.Movies.Response)
    func presentTopRated(response: Home.Movies.Response)
    
    func presentTreiler(response: Home.MoviePreview.Response)
}

class HomePresenter: HomePresentationLogic
{

  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do something
  
  func presentMovies(response: Home.Movies.Response)
  {
      let viewModel = Home.Movies.ViewModel(movies: response.movies)
    viewController?.displayMovies(viewModel: viewModel)
  }
func presentTrendingTv(response: Home.Movies.Response) {
        let viewModel = Home.Movies.ViewModel(movies: response.movies)
      viewController?.displayTrendingTv(viewModel: viewModel)
    }
 func presentPopular(response: Home.Movies.Response) {
     let viewModel = Home.Movies.ViewModel(movies: response.movies)
     viewController?.displayPopular(viewModel: viewModel)
 }
 
 func presentUpcomingMovies(response: Home.Movies.Response) {
     let viewModel = Home.Movies.ViewModel(movies: response.movies)
   viewController?.displayUpcomingMovies(viewModel: viewModel)
 }
 
 func presentTopRated(response: Home.Movies.Response) {
     let viewModel = Home.Movies.ViewModel(movies: response.movies)
     viewController?.displayToprated(viewModel: viewModel)
 }
 
    func presentTreiler(response: Home.MoviePreview.Response) {
        viewController?.displayMoviePreview(viewModel: Home.MoviePreview.ViewModel())
    }
}
